spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: "update"

jwt:
  secret: ${JWT_SECRET}

server:
  host-url: ${HOST_URL}
  port: ${PORT}